-- =============================================================================
-- COCKPIT AGENT — views_v21plus.sql
-- Surcharges pour Sage 100 v21+ (aucune pour l'instant).
-- Toutes les vues sont définies dans views_stable.sql.
-- =============================================================================
-- (Fichier intentionnellement vide — ne rien ajouter ici sans s'assurer
--  que views_stable.sql ne contient pas déjà la même vue)
