-- =============================================================================
-- COCKPIT AGENT — views_fallback.sql
-- Surcharges pour bases Sage 100 très anciennes (aucune pour l'instant).
-- Toutes les vues sont définies dans views_stable.sql.
-- =============================================================================
-- (Fichier intentionnellement vide — ne rien ajouter ici sans s'assurer
--  que views_stable.sql ne contient pas déjà la même vue)
